import { BunTorrentError } from '../../utils/errors';

export enum BencodeDecodeErrorCode {
    // Global
    BAD_FORMAT = 'BENCODE_BAD_FORMAT',
    BUFFER_OVERFLOW = 'BENCODE_BUFFER_OVERFLOW',
    EXPECTED_DELIM = 'BENCODE_EXPECTED_DELIM',
    TRAILING_DATA = 'BENCODE_TRAILING_DATA',
    UNSAFE_INTEGER = 'BENCODE_UNSAFE_INTEGER',
    // Integer
    EXPECTED_INTEGER = 'BENCODE_EXPECTED_INTEGER',
    MISSING_INTEGER_DIGITS = 'BENCODE_MISSING_INTEGER_DIGITS',
    LEADING_ZERO = 'BENCODE_LEADING_ZERO',
    NEGATIVE_ZERO = 'BENCODE_NEGATIVE_ZERO',
    UNTERMINATED_INTEGER = 'BENCODE_UNTERMINATED_INTEGER',
    // Bytes
    EXPECTED_DIGIT = 'BENCODE_EXPECTED_DIGIT',
    MAX_SIZE_EXCEEDED = 'BENCODE_MAX_SIZE_EXCEEDED',
    // List
    EXPECTED_LIST_FLAG = 'BENCODE_EXPECTED_LIST_FLAG',
    UNTERMINATED_LIST = 'BENCODE_UNTERMINATED_LIST',
    // Dict
    EXPECTED_DICT_FLAG = 'BENCODE_EXPECTED_DICT_FLAG',
    DUPLICATE_KEY = 'BENCODE_DUPLICATE_DICT_KEY',
    UNTERMINATED_DICT = 'BENCODE_UNTERMINATED_DICT',
}

export class BencodeDecodeError extends BunTorrentError {
    constructor(
        code: BencodeDecodeErrorCode,
        message: string,
        public readonly offset: number,
    ) {
        super(message, code);
    }
}
